name: Azure Static Web Apps Deployment

on:
  push:
    branches:
      - main  # or change to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Static HTML to Azure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload static files
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations
          action: "upload"
          #### Adjust these as needed
          app_location: "/"            # Root directory
          output_location: "/"         # Output (static files already in root)
